CREATE DATABASE QUANAO
GO
USE QUANAO
GO

CREATE TABLE THUONGHIEU 
(
	IDTHUONGHIEU INT IDENTITY (1,1), 
	TENTHUONGHIEU NVARCHAR (100),
	CONSTRAINT PK_THUONGHIEU PRIMARY KEY (IDTHUONGHIEU)
)
GO
CREATE TABLE LOAISANPHAM
(
	IDLOAISP INT IDENTITY(1,1),
	TENLOAI NVARCHAR(50), 
	CONSTRAINT PK_LOAISANPHAM PRIMARY KEY (IDLOAISP)
)
GO
CREATE TABLE SANPHAMRIENG
(
	IDSPRIENG INT IDENTITY (1,1), 
	IDLOAISP INT,
	TENSANPHAMRIENG NVARCHAR(200)
	CONSTRAINT PK_SANPHAMRIENG PRIMARY KEY (IDSPRIENG),
	CONSTRAINT FK_LOAISANPHAM FOREIGN KEY (IDLOAISP) REFERENCES LOAISANPHAM(IDLOAISP)
)
GO
CREATE TABLE SANPHAM
(
	IDSP INT IDENTITY(1,1),
	TENSANPHAM NVARCHAR (MAX), 
	IDTHUONGHIEU INT , 
	IDSPRIENG INT,
	SIZE NVARCHAR(10),
	GIABAN INT,
	SOLUONGTON INT CHECK (SOLUONGTON >= 0), 
	MOTA NVARCHAR (MAX),
	HINHANH NCHAR(50),
	MAUSAC NVARCHAR(50),
	CHATLIEU NVARCHAR (50),
	GIOITINH NVARCHAR (10),
	KHUYENMAI FLOAT
	CONSTRAINT PK_QUAN PRIMARY KEY (IDSP),
	CONSTRAINT FK_THUONGHIEU FOREIGN KEY (IDTHUONGHIEU) REFERENCES THUONGHIEU(IDTHUONGHIEU),
	CONSTRAINT FK_SANPHAMRIENG FOREIGN KEY (IDSPRIENG) REFERENCES SANPHAMRIENG(IDSPRIENG),
	
)
GO
CREATE TABLE KHACHHANG 
(
	IDKH INT IDENTITY(1,1),
	HOTEN NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE, 
	DIACHIKH NVARCHAR(200),
	DIENTHOAI VARCHAR(50),
	GIOITINH NVARCHAR(10),
	TAIKHOAN VARCHAR(50) UNIQUE, 
	MATKHAU VARCHAR(50)NOT NULL, 
	NGAYSINH DATETIME 
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (IDKH)
)

GO
CREATE TABLE DONHANG 
(
	IDHD INT IDENTITY (1,1),
	NGAYGIAO DATETIME , 
	NGAYDAT DATETIME, 
	DATHANHTOAN BIT, 
	TINHTRANGGIAODICH BIT, 
	IDKH INT 
	CONSTRAINT PK_DONHANG PRIMARY KEY (IDHD),
	CONSTRAINT FK_KHACHHANG FOREIGN KEY (IDKH) REFERENCES KHACHHANG(IDKH)
)
GO
CREATE TABLE CTDONHANG
(
	IDHD INT, 
	IDSP INT, 
	SOLUONG INT CHECK (SOLUONG >0 ), 
	DONGIA DECIMAL (18,0) CHECK (DONGIA > = 0 ),
	CONSTRAINT PK_CTDONHANG PRIMARY KEY (IDHD,IDSP),
	CONSTRAINT FK_DONHANG FOREIGN KEY ( IDHD) REFERENCES DONHANG (IDHD),
	CONSTRAINT FK_SANPHAM FOREIGN KEY (IDSP) REFERENCES SANPHAM (IDSP)
)


INSERT INTO THUONGHIEU VALUES ('PT200')
INSERT INTO THUONGHIEU VALUES ('BRAZZERS')

INSERT INTO LOAISANPHAM VALUES ('QUẦN')
INSERT INTO LOAISANPHAM VALUES ('ÁO')
INSERT INTO LOAISANPHAM VALUES ('NÓN')
INSERT INTO LOAISANPHAM VALUES ('VÁY')

INSERT INTO SANPHAMRIENG VALUES (1,'QUẦN SHORT')
INSERT INTO SANPHAMRIENG VALUES (2,'ÁO VẾU')
INSERT INTO SANPHAMRIENG VALUES (3,'NÓN LƯỠI TRAI')
INSERT INTO SANPHAMRIENG VALUES (4,'VÁY SHORT')

INSERT INTO SANPHAM VALUES ('QUẦN SHORT NAM MÙA HÈ',1,1,'M',300000,10,'NGON LÀNH',1,'ĐEN','KAKI','NAM',0.0)
INSERT INTO SANPHAM VALUES ('QUẦN SHORT NAM MÙA HÈ',1,1,'M',300000,10,'NGON LÀNH',1,'ĐEN','KAKI','NAM',0.0)



